name: CI

on: [push]

jobs:
  build:

    runs-on: buster

    steps:
    - uses: actions/checkout@v1
    - uses: uraimo/run-on-arch-action@v1.0.5
    - name: Build raspian image
      id: runcmd
      with:
        architecture: armv7
        distribution: buster
        run: ./build_image.sh
